#!/usr/bin/env bash

if (( $# == 0 )); then
	read -p "Enter a script name: " name
else
	name=$1
fi

if [[ -z "$name" ]]; then
	echo "Error: No script name provided." >&2
	exit 1
fi

if [[ -e "$name" ]]; then
	echo "Error: '$name' already exists." >&2
	exit 1
fi

echo "#!/usr/bin/env bash" > "$name"
chmod +x "$name"
echo "Script '$name' successfully created."
