#!/usr/bin/env bash

if (( $# == 0 )); then
	read -p "Enter a script name: " name
else
	name=$1
fi

touch $name
echo "#!/usr/bin/env bash" > $name
chmod +x $name
echo "Script $name successfully created."
